spring.application.name=event-service
spring.data.mongodb.host=mongo
spring.data.mongodb.port=27017
spring.data.mongodb.database=bank_of_georgia
spring.kafka.bootstrap-servers=kafka:9092
server.port=8081